### ISSUE TITLE
Kafka Connect support

### ISSUE THREAD

**Issue by mcandre** [sous-chefs/kafka#103]
Does kafka-cookbook support deploying Kafka Connect nodes? If so, could the documentation include information about setting this up?

If not, could another recipe be uploaded for Kafka Connect?

**Comment by mthssdrbrg** [comment]
It currently does not.

I haven't really thought about adding Kafka Connect support, and the (original) purpose of this cookbook was to provision brokers. However, I guess it would make sense to use this cookbook to provision Connect nodes as well. To be honest I'm not very familiar with how one would go about deploying Connect, so I would have to look into it a bit.

**Comment by mthssdrbrg** [comment]
I currently don't have the time to investigate this, but I'll leave it open for a little bit longer. I added a "help wanted' label, in case anyone wants to help with some research how one would go about supporting Kafka Connect deployments.
