### ISSUE TITLE
Sous-chefs would like to adopt your cookbook. 

### ISSUE THREAD

**Issue by damacus** [sous-chefs/kafka#151]
Hey there! 

we over at sous-chefs would like to adopt your cookbook, so that the community can continue benefiting of the good work you're doing, and gain the newest features of the Chef ecosystem. 

We already have a [number of widely used cookbooks ](https://github.com/sous-chefs/) which you might be familiar with. 

The transfer procedure can be found [on our website here](https://sous-chefs.org/transferring/).

Thanks!
Dan

**Comment by mthssdrbrg** [comment]
Hey @damacus 

Sorry for the _really_ _really_ late reply, but I've started the process of transferring this over: https://github.com/sous-chefs/terraform-github-org/pull/136

**Comment by damacus** [comment]
No problem it usually goes that way!

You should be invited to the org now, so feel free to move it over at your convenience.

**Comment by mthssdrbrg** [comment]
I've transferred (as you can see :sweat_smile:) the repository tonight, just a couple of months late.

I presume that it'll be renamed to just `kafka` and whatever references that are in the repository itself (to itself) will be dealt with?

I'll have a look at doing the transfer on Supermarket as well.

**Comment by damacus** [comment]
Thanks!
